project:
  type: book
  output-dir: docs

book:
  title: "Principal Component Analysis"
  author: "Hector Gavilanes, Gail Han, Michael T. Mezzano"
  date: "11/05/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - examples.qmd
    - dataset.qmd
    - analysis.qmd
    - results.qmd
    - references.qmd

bibliography: references.bib
csl: ieee-with-url.csl

format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "Show the code"
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  freeze: auto