project:
  type: book
  output-dir: docs

book:
  title: "Principal Component Analysis"
  author: "Michael T. Mezzano, Gail Han, Hector Gavilanes"
  date: "9/27/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
csl: ieee-with-url.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

