<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Principal Component Analysis - 3&nbsp; Examples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./dataset.html" rel="next">
<link href="./methods.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./examples.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Examples</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Principal Component Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./examples.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Examples</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataset.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Dataset</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Results and Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#manual-calculation-of-principal-components" id="toc-manual-calculation-of-principal-components" class="nav-link active" data-scroll-target="#manual-calculation-of-principal-components"><span class="header-section-number">3.1</span> Manual calculation of principal components</a>
  <ul class="collapse">
  <li><a href="#calculate-the-covariance-matrix-m" id="toc-calculate-the-covariance-matrix-m" class="nav-link" data-scroll-target="#calculate-the-covariance-matrix-m"><span class="header-section-number">3.1.1</span> Calculate the covariance matrix <span class="math inline">\(M\)</span></a></li>
  <li><a href="#compute-the-singular-value-decomposition-svd" id="toc-compute-the-singular-value-decomposition-svd" class="nav-link" data-scroll-target="#compute-the-singular-value-decomposition-svd"><span class="header-section-number">3.1.2</span> Compute the singular value decomposition (SVD)</a></li>
  <li><a href="#derive-the-new-dataset" id="toc-derive-the-new-dataset" class="nav-link" data-scroll-target="#derive-the-new-dataset"><span class="header-section-number">3.1.3</span> Derive The new dataset</a></li>
  <li><a href="#verifying-and-visualizing-the-results" id="toc-verifying-and-visualizing-the-results" class="nav-link" data-scroll-target="#verifying-and-visualizing-the-results"><span class="header-section-number">3.1.4</span> Verifying and visualizing the results</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">3.1.5</span> Summary</a></li>
  </ul></li>
  <li><a href="#pca-on-a-large-dataset-using-r" id="toc-pca-on-a-large-dataset-using-r" class="nav-link" data-scroll-target="#pca-on-a-large-dataset-using-r"><span class="header-section-number">3.2</span> PCA on a large dataset using R</a>
  <ul class="collapse">
  <li><a href="#libraries" id="toc-libraries" class="nav-link" data-scroll-target="#libraries"><span class="header-section-number">3.2.1</span> Libraries</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation"><span class="header-section-number">3.2.2</span> Data Preparation</a></li>
  <li><a href="#feature-scaling" id="toc-feature-scaling" class="nav-link" data-scroll-target="#feature-scaling"><span class="header-section-number">3.2.3</span> Feature Scaling</a></li>
  <li><a href="#pca-via-singular-value-decomposition" id="toc-pca-via-singular-value-decomposition" class="nav-link" data-scroll-target="#pca-via-singular-value-decomposition"><span class="header-section-number">3.2.4</span> PCA via Singular Value Decomposition</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization"><span class="header-section-number">3.2.5</span> Visualization</a></li>
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1"><span class="header-section-number">3.2.6</span> Summary</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Examples</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Moving beyond the theoretical foundations of principal components, how is PCA applied to data? We offer two examples; the first a demonstration of the manual calculation of principal components, and the second implementing PCA on a large dataset using R.</p>
<section id="manual-calculation-of-principal-components" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="manual-calculation-of-principal-components"><span class="header-section-number">3.1</span> Manual calculation of principal components</h2>
<p>In this illustration, we have access to the two grades of four students in a statistics subject. We aim to employ principal component analysis as a means to reduce the dimensionality from two variables to a singular variable. This transformation will effectively represent students’ performance in the subject with a more compact and interpretable measure. This example is adapted from the resource <em>How to compute principal components</em> <span class="citation" data-cites="eduflair2020"><a href="references.html#ref-eduflair2020" role="doc-biblioref">[1]</a></span>.</p>
<table class="table">
<thead>
<tr class="header">
<th>Scores</th>
<th><strong>Basic Stats</strong></th>
<th><strong>Advanced Stats</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Student 1</strong></td>
<td><strong>4</strong></td>
<td><strong>11</strong></td>
</tr>
<tr class="even">
<td><strong>Student 2</strong></td>
<td><strong>8</strong></td>
<td><strong>4</strong></td>
</tr>
<tr class="odd">
<td><strong>Student 3</strong></td>
<td><strong>13</strong></td>
<td><strong>5</strong></td>
</tr>
<tr class="even">
<td><strong>Student 4</strong></td>
<td><strong>7</strong></td>
<td><strong>14</strong></td>
</tr>
<tr class="odd">
<td><strong>Mean</strong></td>
<td><span class="math inline">\(\bar{x}\)</span>=8</td>
<td><span class="math inline">\(\bar{y}\)</span>=8.5</td>
</tr>
</tbody>
</table>
<section id="calculate-the-covariance-matrix-m" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="calculate-the-covariance-matrix-m"><span class="header-section-number">3.1.1</span> Calculate the covariance matrix <span class="math inline">\(M\)</span></h3>
<p><span class="math display">\[
\begin{bmatrix}
\text{cov}(x,x) &amp; \text{cov}(x,y) \\
\text{cov}(y,x) &amp; \text{cov}(y,y) \\
\end{bmatrix}
\]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(\text{cov}(x,x)\)</span> = <span class="math inline">\(\text{var}(x)\)</span> = <span class="math inline">\(\mathbf{E}\)</span>(<span class="math inline">\(x^2\)</span>) - <span class="math inline">\(\mathbf{E}\)</span> <span class="math inline">\((x)^2\)</span> = <span class="math display">\[ \frac{(16+0+25+1)}{3}=14 \]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(\text{cov}(y,y)\)</span> = <span class="math inline">\(\text{var}(y)\)</span> = <span class="math inline">\(\mathbf{E}\)</span>(<span class="math inline">\(y^2\)</span>) - <span class="math inline">\(\mathbf{E}\)</span> <span class="math inline">\((y)^2\)</span> = <span class="math display">\[ \frac{(6.25+20.25+12.25+30.25)}{3}=23 \]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(\text{cov}(x,y)\)</span> = <span class="math inline">\(\text{cov}(y,x)\)</span> = <span class="math inline">\(\mathbf{E}\)</span>(<span class="math inline">\(xy\)</span>) - <span class="math inline">\(\mathbf{E}\)</span> (<span class="math inline">\(x\)</span>)<span class="math inline">\(\mathbf{E}\)</span> (<span class="math inline">\(y\)</span>) = <span class="math display">\[ \frac{(-10+0-17.5-5.5)}{3}=-11 \]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> Covariance Matrix <span class="math inline">\(M\)</span> <span class="math display">\[
\begin{bmatrix}
14 &amp; -11 \\
-11 &amp; 23 \\
\end{bmatrix} \]</span></p>
</section>
<section id="compute-the-singular-value-decomposition-svd" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="compute-the-singular-value-decomposition-svd"><span class="header-section-number">3.1.2</span> Compute the singular value decomposition (SVD)</h3>
<p>We can obtain the principal components and loadings from SVD of the covariance matrix M since covariance matrix M is a square matrix:</p>
<p><span class="math display">\[
\begin{bmatrix}
14 &amp; -11 \\
-11 &amp; 23 \\
\end{bmatrix} \times Any\ vector = \lambda \times Any\ vector\ ,\ (vector\neq 0)
\]</span></p>
<p><span class="math display">\[det(M - \lambda I) = 0\]</span></p>
<section id="obtain-eigenvalues-of-the-covariance-matrix-rightarrow-lambda_1-lambda_2" class="level4" data-number="3.1.2.1">
<h4 data-number="3.1.2.1" class="anchored" data-anchor-id="obtain-eigenvalues-of-the-covariance-matrix-rightarrow-lambda_1-lambda_2"><span class="header-section-number">3.1.2.1</span> Obtain eigenvalues of the covariance matrix <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\lambda_1\)</span> &amp; <span class="math inline">\(\lambda_2\)</span></h4>
<p><span class="math display">\[
I = \begin{bmatrix}
1 &amp; 0 \\
0 &amp; 1 \\
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\lambda I = \lambda \times \begin{bmatrix}
1 &amp; 0 \\
0 &amp; 1 \\
\end{bmatrix} = \begin{bmatrix}
\lambda  &amp; 0 \\
0 &amp; \lambda  \\
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\begin{bmatrix}
14 &amp; -11 \\
-11&amp;  23 \\
\end{bmatrix} -\begin{bmatrix}
\lambda  &amp; 0 \\
0 &amp; \lambda  \\
\end{bmatrix} = \begin{bmatrix}
14-\lambda  &amp; -11 \\
-11 &amp; 23-\lambda  \\
\end{bmatrix}
\]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span></p>
<p><span class="math display">\[
det\begin{bmatrix}
14-\lambda &amp; -11 \\
-11&amp; 23-\lambda  \\
\end{bmatrix}=0
\]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math display">\[(14-\lambda)(23-\lambda) - (-11)(-11) = 0 \]</span></p>
<p><span class="math display">\[\lambda^2 +37\lambda -201 = 0\]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(\lambda_1\)</span> = 30.3849, <span class="math inline">\(\lambda_2\)</span> = 6.6152 (eigenvalues for Covariance Matrix <span class="math inline">\(M\)</span>)</p>
</section>
<section id="obtain-eigenvector-of-lambda_1" class="level4" data-number="3.1.2.2">
<h4 data-number="3.1.2.2" class="anchored" data-anchor-id="obtain-eigenvector-of-lambda_1"><span class="header-section-number">3.1.2.2</span> Obtain eigenvector of <span class="math inline">\(\lambda_1\)</span></h4>
<p><span class="math display">\[(M - \lambda_1I)\times U_1 = \mathbf{0} \]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math display">\[\begin{bmatrix}
14-\lambda &amp; -11 \\
-11&amp; 23-\lambda  \\
\end{bmatrix}\times\begin{bmatrix}
u_1 \\
u_2 \\
\end{bmatrix}=\mathbf{0}
\]</span></p>
<p><span class="math display">\[(14- \lambda)u_1 - 11u_2 = 0 \]</span> <span class="math inline">\(\Rightarrow\)</span> <span class="math display">\[-16.3849u_1 -11u_2 = 0\]</span> <span class="math inline">\(\Rightarrow\)</span> <span class="math display">\[-16.3849u_1= 11u_2 \]</span> <span class="math inline">\(\Rightarrow\)</span> <span class="math display">\[u_1 = \frac{11}{-16.3849}u_2\]</span></p>
<p><span class="math display">\[
\begin{bmatrix}
u_1 \\
u_2 \\
\end{bmatrix}= u_2\begin{bmatrix}
\frac{11}{-16.3849}\\
1 \\
\end{bmatrix}
\]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math display">\[u_2\begin{bmatrix}
-11\\ 16.3849
\end{bmatrix}\]</span></p>
<p><span class="math display">\[
\begin{bmatrix}
16.3849 &amp; 11 \\
\end{bmatrix} \times \begin{bmatrix}
u_1 \\ u_2
\end{bmatrix} = \begin{bmatrix}
11 \\ -16.3849
\end{bmatrix}
\]</span></p>
<p><strong>Normalized Eigenvector</strong></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(\lambda_1\)</span>: <span class="math inline">\(e_1\)</span></p>
<p><span class="math display">\[
\frac{1}{\sqrt{{11^2 +16.3849^2}}}\begin{bmatrix}
11 \\ -16.3849
\end{bmatrix}= \begin{bmatrix}
0.5574 \\ -0.8303
\end{bmatrix}
\]</span></p>
<p><span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(\lambda_2\)</span> <span class="math inline">\(e_2\)</span> (Right singular vector) =</p>
<p><span class="math display">\[
\begin{bmatrix}
0.8303 \\ 0.5574
\end{bmatrix}
\]</span></p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th><strong>Basic Stats</strong></th>
<th><strong>Advanced Stats</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Student 1</strong></td>
<td><strong>4</strong></td>
<td><strong>11</strong></td>
</tr>
<tr class="even">
<td><strong>Student 2</strong></td>
<td><strong>8</strong></td>
<td><strong>4</strong></td>
</tr>
<tr class="odd">
<td><strong>Student 3</strong></td>
<td><strong>13</strong></td>
<td><strong>5</strong></td>
</tr>
<tr class="even">
<td><strong>Student 4</strong></td>
<td><strong>7</strong></td>
<td><strong>14</strong></td>
</tr>
<tr class="odd">
<td><strong>Mean</strong></td>
<td><span class="math inline">\(\bar{x}\)</span>=8</td>
<td><span class="math inline">\(\bar{y}\)</span>=8.5</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="derive-the-new-dataset" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="derive-the-new-dataset"><span class="header-section-number">3.1.3</span> Derive The new dataset</h3>
<p><strong>First Principal Component (PC1)</strong></p>
<p><span class="math display">\[
P_{11} = e_1^T \times
\begin{bmatrix}
4-mean(x) \\ 11 -mean(y)
\end{bmatrix}
= \begin{bmatrix}
0.5574 &amp; -0.8303 \\
\end{bmatrix}
\begin{bmatrix}
4-8 \\ 11-8.5
\end{bmatrix} =-4.3052
\]</span></p>
<p><span class="math display">\[
P_{12} = e_1^T \times
\begin{bmatrix}
8-mean(x) \\ 4 -mean(y)
\end{bmatrix}
= \begin{bmatrix}
0.5574 &amp; -0.8303 \\
\end{bmatrix}
\begin{bmatrix}
8-8 \\ 4-8.5
\end{bmatrix} =3.7361
\]</span></p>
<p><span class="math display">\[
P_{13} = e_1^T \times
\begin{bmatrix}
13-mean(x) \\ 5 -mean(y)
\end{bmatrix}
= \begin{bmatrix}
0.5574 &amp; -0.8303 \\
\end{bmatrix}
\begin{bmatrix}
13-8 \\ 5-8.5
\end{bmatrix}= 5.6928
\]</span></p>
<p><span class="math display">\[
P_{14}= e_1^T \times
\begin{bmatrix}
7-mean(x) \\ 14 -mean(y)
\end{bmatrix}
= \begin{bmatrix}
0.5574 &amp; -0.8303 \\
\end{bmatrix}
\begin{bmatrix}
7-8 \\ 14-8.5
\end{bmatrix} = -5.1238
\]</span></p>
<!-- -->
<p><strong>The new dataset (Left singular vector)</strong></p>
<table class="table">
<colgroup>
<col style="width: 38%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>First Principal Component (PC1)</strong></th>
<th style="text-align: center;"><strong>Student 1</strong></th>
<th style="text-align: center;"><strong>Student 2</strong></th>
<th style="text-align: center;"><strong>Student 3</strong></th>
<th style="text-align: center;"><strong>Student 4</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>-4.3052</strong></td>
<td style="text-align: center;"><strong>3.7361</strong></td>
<td style="text-align: center;"><strong>5.6928</strong></td>
<td style="text-align: center;"><strong>-5.1238</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="verifying-and-visualizing-the-results" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="verifying-and-visualizing-the-results"><span class="header-section-number">3.1.4</span> Verifying and visualizing the results</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4 obs. of  3 variables:
 $ Student      : int  1 2 3 4
 $ BasicStats   : num  4 8 13 7
 $ AdvancedStats: num  11 4 5 14</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2
Standard deviation     1.2700 0.6221
Proportion of Variance 0.8065 0.1935
Cumulative Proportion  0.8065 1.0000</code></pre>
</div>
<div class="cell-output-display">
<p><img src="examples_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="examples_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="summary" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="summary"><span class="header-section-number">3.1.5</span> Summary</h3>
<p>The first principal component of the data captures 80.7% of the variation (or information) while reducing the dimensionality of the dataset from 2 variables to 1. Small datasets such as this make the hand-calculation of principal components feasible and easy to follow, but the strengths of PCA are especially evident when software is used to enable principal component analysis for large datasets. In the next example, we demonstrate how PCA can be used with a large dataset using the R programming language.</p>
</section>
</section>
<section id="pca-on-a-large-dataset-using-r" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="pca-on-a-large-dataset-using-r"><span class="header-section-number">3.2</span> PCA on a large dataset using R</h2>
<p>For this application of PCA, the Abalone dataset from the UCI Machine Learning Repository is used <span class="citation" data-cites="misc_abalone_1"><a href="references.html#ref-misc_abalone_1" role="doc-biblioref">[2]</a></span>. This dataset contain 4177 observations of 9 variables which record characteristics of each abalone including sex, length, diameter, height, weights, and the number of rings. The variables, apart from sex, are continuous and correlated making the dataset an ideal candidate for demonstrating dimensionality reduction via PCA.</p>
<section id="libraries" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="libraries"><span class="header-section-number">3.2.1</span> Libraries</h3>
<p>First, the appropriate and necessary libraries are loaded in R. These provide the functions which serve as the backbone of the analysis, handling the computational aspects of PCA as well as visualizing the results.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)  <span class="co"># for handling missing values</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot) <span class="co"># for plotting the correlation matrix</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra) <span class="co"># PCA plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="data-preparation" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="data-preparation"><span class="header-section-number">3.2.2</span> Data Preparation</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># clear environment</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load dataset</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>abalone <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'./abalone/abalone.csv'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset structure</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(abalone)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4177 obs. of  9 variables:
 $ Sex           : chr  "M" "M" "F" "M" ...
 $ Length        : num  0.455 0.35 0.53 0.44 0.33 0.425 0.53 0.545 0.475 0.55 ...
 $ Diameter      : num  0.365 0.265 0.42 0.365 0.255 0.3 0.415 0.425 0.37 0.44 ...
 $ Height        : num  0.095 0.09 0.135 0.125 0.08 0.095 0.15 0.125 0.125 0.15 ...
 $ Whole_weight  : num  0.514 0.226 0.677 0.516 0.205 ...
 $ Shucked_weight: num  0.2245 0.0995 0.2565 0.2155 0.0895 ...
 $ Viscera_weight: num  0.101 0.0485 0.1415 0.114 0.0395 ...
 $ Shell_weight  : num  0.15 0.07 0.21 0.155 0.055 0.12 0.33 0.26 0.165 0.32 ...
 $ Rings         : int  15 7 9 10 7 8 20 16 9 19 ...</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Missing values</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(abalone))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           Sex         Length       Diameter         Height   Whole_weight 
             0              0              0              0              0 
Shucked_weight Viscera_weight   Shell_weight          Rings 
             0              0              0              0 </code></pre>
</div>
</div>
<p>The dataset contains 9 variables with 1 categorical variable and 8 numeric variables. The dataset contains no missing values. For this example in applying principal component analysis, we exclude the categorical variable ‘Sex’ and focus the PCA on the numerical dimensions of the Abalone. For analyses involving a mix of numeric and non-numeric variables other factor analysis techniques can be used, such as factor analysis of mixed data <span class="citation" data-cites="pages2014multiple"><a href="references.html#ref-pages2014multiple" role="doc-biblioref">[3]</a></span>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only the numeric variables </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>abalone <span class="ot">&lt;-</span> abalone <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">where</span>(is.numeric))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(abalone)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     Length         Diameter          Height        Whole_weight   
 Min.   :0.075   Min.   :0.0550   Min.   :0.0000   Min.   :0.0020  
 1st Qu.:0.450   1st Qu.:0.3500   1st Qu.:0.1150   1st Qu.:0.4415  
 Median :0.545   Median :0.4250   Median :0.1400   Median :0.7995  
 Mean   :0.524   Mean   :0.4079   Mean   :0.1395   Mean   :0.8287  
 3rd Qu.:0.615   3rd Qu.:0.4800   3rd Qu.:0.1650   3rd Qu.:1.1530  
 Max.   :0.815   Max.   :0.6500   Max.   :1.1300   Max.   :2.8255  
 Shucked_weight   Viscera_weight    Shell_weight        Rings       
 Min.   :0.0010   Min.   :0.0005   Min.   :0.0015   Min.   : 1.000  
 1st Qu.:0.1860   1st Qu.:0.0935   1st Qu.:0.1300   1st Qu.: 8.000  
 Median :0.3360   Median :0.1710   Median :0.2340   Median : 9.000  
 Mean   :0.3594   Mean   :0.1806   Mean   :0.2388   Mean   : 9.934  
 3rd Qu.:0.5020   3rd Qu.:0.2530   3rd Qu.:0.3290   3rd Qu.:11.000  
 Max.   :1.4880   Max.   :0.7600   Max.   :1.0050   Max.   :29.000  </code></pre>
</div>
</div>
<p>The summary statistics show the differences in measurement between variables, with some variables such as diameter and viscera weight having small ranges and others, namely rings, having relatively large ranges. For this reason, scaling of the variables is a crucial step in PCA to ensure results accurately capture the variance in the data.</p>
</section>
<section id="feature-scaling" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="feature-scaling"><span class="header-section-number">3.2.3</span> Feature Scaling</h3>
<p>Standardization ensures all variables, also called features, are on the same scale, and the scale function allows us to center the data to a mean of 0 and variance of 1. This ensures no single feature has an outsized effect during the principal component analysis.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardization of numerical features</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>abalone_sc <span class="ot">&lt;-</span> <span class="fu">scale</span>(abalone, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(abalone_sc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     Length           Diameter           Height          Whole_weight     
 Min.   :-3.7387   Min.   :-3.5558   Min.   :-3.33555   Min.   :-1.68589  
 1st Qu.:-0.6161   1st Qu.:-0.5832   1st Qu.:-0.58614   1st Qu.:-0.78966  
 Median : 0.1749   Median : 0.1725   Median : 0.01156   Median :-0.05963  
 Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.00000   Mean   : 0.00000  
 3rd Qu.: 0.7578   3rd Qu.: 0.7267   3rd Qu.: 0.60926   3rd Qu.: 0.66123  
 Max.   : 2.4232   Max.   : 2.4397   Max.   :23.68045   Max.   : 4.07178  
 Shucked_weight    Viscera_weight      Shell_weight         Rings        
 Min.   :-1.6145   Min.   :-1.64298   Min.   :-1.7049   Min.   :-2.7708  
 1st Qu.:-0.7811   1st Qu.:-0.79455   1st Qu.:-0.7818   1st Qu.:-0.5997  
 Median :-0.1053   Median :-0.08752   Median :-0.0347   Median :-0.2896  
 Mean   : 0.0000   Mean   : 0.00000   Mean   : 0.0000   Mean   : 0.0000  
 3rd Qu.: 0.6426   3rd Qu.: 0.66056   3rd Qu.: 0.6478   3rd Qu.: 0.3307  
 Max.   : 5.0848   Max.   : 5.28587   Max.   : 5.5040   Max.   : 5.9136  </code></pre>
</div>
</div>
<p>Viewing the data after scaling and centering, values greater than 3 or less than -3 represent outliers more than 3 standard deviations from the mean. Based on the ranges of the variables, we should view a boxplot of the data to further investigate.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot a boxplot to visualize potential outliers</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="dv">4</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(abalone_sc, <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">main =</span> <span class="st">"Visualization of scaled and centered data"</span>, <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">las =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="examples_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Are there enough outliers to be a cause for concern? We can see how many lie outside of the third standard deviation of the data for each variable.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colSums</span>(abalone_sc <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">|</span> abalone_sc <span class="sc">&lt;</span> <span class="sc">-</span><span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        Length       Diameter         Height   Whole_weight Shucked_weight 
            15             13              5             19             37 
Viscera_weight   Shell_weight          Rings 
            22             27             62 </code></pre>
</div>
</div>
<p>Of the 4177 observations, at most 62 in a single variable (rings) are outliers. The tolerance for outliers will differ depending on the investigation, but for our illustrative purposes this number is well within tolerance for principal component analysis.</p>
<p>Lastly, we can investigate the correlation among the variables. PCA is best used with linearly correlated data. If the data is not correlated, the results of PCA will be less meaningful.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlations and round to 2 digits</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>abalone_corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(abalone_sc)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(abalone_corr, <span class="at">method=</span><span class="st">"number"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="examples_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Our scaled and centered data has strong linear correlations and contains a relatively small number of outliers. We can now calculate the principal components of the dataset.</p>
</section>
<section id="pca-via-singular-value-decomposition" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="pca-via-singular-value-decomposition"><span class="header-section-number">3.2.4</span> PCA via Singular Value Decomposition</h3>
<p>The prcomp() function <span class="citation" data-cites="prcomp2023ref"><a href="references.html#ref-prcomp2023ref" role="doc-biblioref">[4]</a></span> performs principal component analysis on a dataset using the singular value decomposition method, which utilizes the covariance matrix of the data.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply PCA using prcomp()</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>abalone_pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(abalone_sc)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(abalone_pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                         PC1     PC2     PC3     PC4     PC5     PC6     PC7
Standard deviation     2.591 0.83403 0.50837 0.40742 0.29146 0.25194 0.11267
Proportion of Variance 0.839 0.08695 0.03231 0.02075 0.01062 0.00793 0.00159
Cumulative Proportion  0.839 0.92601 0.95831 0.97906 0.98968 0.99761 0.99920
                           PC8
Standard deviation     0.07999
Proportion of Variance 0.00080
Cumulative Proportion  1.00000</code></pre>
</div>
</div>
<section id="pca---cumulative-variance-and-number-of-principal-components" class="level4" data-number="3.2.4.1">
<h4 data-number="3.2.4.1" class="anchored" data-anchor-id="pca---cumulative-variance-and-number-of-principal-components"><span class="header-section-number">3.2.4.1</span> PCA - Cumulative Variance and Number of Principal Components</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Principal Component scores vector</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>pc_scores <span class="ot">&lt;-</span> abalone_pca<span class="sc">$</span>x</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Std Deviation of Components</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>component_sdev <span class="ot">&lt;-</span> abalone_pca<span class="sc">$</span>sdev</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Eigenvector or Loadings</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>eigenvector <span class="ot">&lt;-</span> abalone_pca<span class="sc">$</span>rotation</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean of variables</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>component_mean <span class="ot">&lt;-</span> abalone_pca<span class="sc">$</span>center </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Scaling factor of Variables</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>component_scale <span class="ot">&lt;-</span> abalone_pca<span class="sc">$</span>scale</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion of variance explained by each PC</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>variance_explained <span class="ot">&lt;-</span> component_sdev<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(component_sdev<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Cumulative proportion of variance explained</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>cumulative_variance_explained <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(variance_explained)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Retain components that explain a percentage of the variance</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>num_components <span class="ot">&lt;-</span> <span class="fu">which</span>(cumulative_variance_explained <span class="sc">&gt;=</span> <span class="fl">0.92</span>)[<span class="dv">1</span>]</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the desired number of principal components</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>selected_pcs <span class="ot">&lt;-</span> pc_scores[, <span class="dv">1</span><span class="sc">:</span>num_components]</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Display cumulative variance</span></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>cumulative_variance_explained</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8390549 0.9260065 0.9583119 0.9790606 0.9896793 0.9976134 0.9992002
[8] 1.0000000</code></pre>
</div>
</div>
<p>The first 2 principal components alone explain 92% of the variance in the data.</p>
</section>
<section id="loading-of-first-two-components" class="level4" data-number="3.2.4.2">
<h4 data-number="3.2.4.2" class="anchored" data-anchor-id="loading-of-first-two-components"><span class="header-section-number">3.2.4.2</span> Loading of First Two Components</h4>
<p>The loading are the weights assigned to each variable for that particular principal component.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access the loadings for the first two principal components</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>loadings_first_two_components <span class="ot">&lt;-</span> eigenvector[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the loadings for the first two principal components</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Loadings for the first two principal components:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Loadings for the first two principal components:"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(loadings_first_two_components)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     PC1         PC2
Length         0.3721385  0.06828270
Diameter       0.3730941  0.04004804
Height         0.3400268 -0.07046315
Whole_weight   0.3783075  0.13734619
Shucked_weight 0.3624545  0.29883992
Viscera_weight 0.3685578  0.17297852
Shell_weight   0.3707578 -0.04540040
Rings          0.2427128 -0.92120385</code></pre>
</div>
</div>
</section>
<section id="pca---elements" class="level4" data-number="3.2.4.3">
<h4 data-number="3.2.4.3" class="anchored" data-anchor-id="pca---elements"><span class="header-section-number">3.2.4.3</span> PCA - Elements</h4>
<p>The values in <strong><code>abalone_pca$x</code></strong> are the coordinates of each observation in the new principal component space. These coordinates are the scores for each observation along each principal component. The eigenvectors of the covariance or correlation matrix of the data represent the directions of maximum variance in the dataset.</p>
</section>
</section>
<section id="visualization" class="level3" data-number="3.2.5">
<h3 data-number="3.2.5" class="anchored" data-anchor-id="visualization"><span class="header-section-number">3.2.5</span> Visualization</h3>
<section id="scree-plot---cumulative-variance-explained" class="level4" data-number="3.2.5.1">
<h4 data-number="3.2.5.1" class="anchored" data-anchor-id="scree-plot---cumulative-variance-explained"><span class="header-section-number">3.2.5.1</span> Scree Plot - Cumulative Variance Explained</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(abalone_pca, <span class="at">addlabels =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="examples_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The scree plot visualizes the variance captured by each PC. PC1 explains 83.9% of the variance, and PC2 explains 8.7% variance.</p>
</section>
<section id="biplot" class="level4" data-number="3.2.5.2">
<h4 data-number="3.2.5.2" class="anchored" data-anchor-id="biplot"><span class="header-section-number">3.2.5.2</span> Biplot</h4>
<p>The correlation between a variable and a principal component is used as the coordinates of the variable on the PC, shown as dimensions on the biplot. Dim1 corresponds to PC1, and Dim2 to PC2. The representation of variables differs from the plot of the observations: The observations are represented by their projections, but the variables are represented by their correlations <span class="citation" data-cites="abdi2010principal"><a href="references.html#ref-abdi2010principal" role="doc-biblioref">[5]</a></span>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_biplot</span>(abalone_pca, <span class="at">label =</span> <span class="st">"var"</span>, <span class="at">alpha.ind =</span> <span class="st">"contrib"</span>, <span class="at">col.var =</span> <span class="st">"blue"</span>, <span class="at">repel =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="examples_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="variable-contribution" class="level4" data-number="3.2.5.3">
<h4 data-number="3.2.5.3" class="anchored" data-anchor-id="variable-contribution"><span class="header-section-number">3.2.5.3</span> Variable Contribution</h4>
<p>Top variable contribution for the first two principal components.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contributions of variables to PC1</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>pc2_contribution <span class="ot">&lt;-</span> <span class="fu">fviz_contrib</span>(abalone_pca, <span class="at">choice =</span> <span class="st">"var"</span>, <span class="at">axes =</span> <span class="dv">1</span>, <span class="at">top =</span> <span class="dv">20</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modify the theme to rotate X-axis labels to 90 degrees</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>pc2_contribution <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>)  <span class="co"># horizontal justification</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Contribution of Variables to PC1"</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Percentage Contribution"</span>,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"PC1 explains 83.9% of the variance"</span>) <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>                                                     <span class="at">accuracy =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="examples_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contributions of variables to PC2</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>pc2_contribution <span class="ot">&lt;-</span> <span class="fu">fviz_contrib</span>(abalone_pca, <span class="at">choice =</span> <span class="st">"var"</span>, <span class="at">axes =</span> <span class="dv">2</span>, <span class="at">top =</span> <span class="dv">12</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modify the theme to rotate X-axis labels to 90 degrees</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>pc2_contribution <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>)  <span class="co"># horizontal justification</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Contribution of Variables to PC2"</span>,</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Percentage Contribution"</span>,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"PC2 explains 8.7% of the variance"</span>) <span class="sc">+</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>                                                     <span class="at">accuracy =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="examples_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="summary-1" class="level3" data-number="3.2.6">
<h3 data-number="3.2.6" class="anchored" data-anchor-id="summary-1"><span class="header-section-number">3.2.6</span> Summary</h3>
<p>The first principal component captures 83.9% of the variance in the data. This linear combination has relatively equal loadings for whole weight, diameter, length, shell weight, viscera weight, and shucked weight, with height and rings having lower loadings. The second principal component is mostly influenced by the variable rings which makes up over 80% of the contribution to PC2. The biplot is an effective visualization of how each variable contributes to PC1, or dimension 1 on the graph, and PC2, or dimension 2 on the graph. The length and direction of each vector represent the contribution of each variable to the principal components; whole weight and rings are the longest, representing the largest contributions to PC1 and PC2 respectively.</p>
<p>PCA is primarily an exploratory tool, which allows us to visualize high-dimensional data in lower dimensions as shown above in the biplot and accompanying scree plot. These PCs can be used to explore data in other ways, such as looking for trends and patterns in the data or identifying clusters and outliers. In the formal analysis in the following chapter, the applications of PCA are further explored through the development of a regression model on the principal components of a dataset.</p>


<div id="refs" class="references csl-bib-body" role="list" style="display: none">
<div id="ref-eduflair2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">E. K. CS, <span>“PCA problem / how to compute principal components / KTU machine learning.”</span> YouTube, 2020. Available: <a href="https://youtu.be/MLaJbA82nzk">https://youtu.be/MLaJbA82nzk</a>. [Accessed: Nov. 01, 2023]</div>
</div>
<div id="ref-misc_abalone_1" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">S. Nash Warwick and W. Ford, <span>“<span>Abalone</span>.”</span> UCI Machine Learning Repository, 1995.</div>
</div>
<div id="ref-pages2014multiple" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">J. Pagès, <em>Multiple factor analysis by example using r</em>. CRC Press, 2014.</div>
</div>
<div id="ref-prcomp2023ref" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">R Core Team, <span>“Prcomp, a function of r: A language and environment for statistical computing.”</span> R Foundation for Statistical Computing, Vienna, Austria, 2023. Available: <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/prcomp">https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/prcomp</a>. [Accessed: Oct. 16, 2023]</div>
</div>
<div id="ref-abdi2010principal" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">H. Abdi and L. Williams, <span>“Principal component analysis. WIREs comp stat 2: 433–459.”</span> 2010.</div>
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./methods.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Methods</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./dataset.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Dataset</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>